# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import heartbeat_pb2 as heartbeat__pb2


class HeartbeatStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendHeartbeat = channel.unary_unary(
        '/Heartbeat/SendHeartbeat',
        request_serializer=heartbeat__pb2.HeartbeatMessage.SerializeToString,
        response_deserializer=heartbeat__pb2.HeartbeatResponse.FromString,
        )
    self.Join = channel.unary_unary(
        '/Heartbeat/Join',
        request_serializer=heartbeat__pb2.JoinRequest.SerializeToString,
        response_deserializer=heartbeat__pb2.JoinResponse.FromString,
        )


class HeartbeatServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendHeartbeat(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Join(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HeartbeatServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendHeartbeat': grpc.unary_unary_rpc_method_handler(
          servicer.SendHeartbeat,
          request_deserializer=heartbeat__pb2.HeartbeatMessage.FromString,
          response_serializer=heartbeat__pb2.HeartbeatResponse.SerializeToString,
      ),
      'Join': grpc.unary_unary_rpc_method_handler(
          servicer.Join,
          request_deserializer=heartbeat__pb2.JoinRequest.FromString,
          response_serializer=heartbeat__pb2.JoinResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Heartbeat', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
